---
- hosts: tomcat
  remote_user: root
  become: yes
  tasks:
  - name: Creates directory
    file:
      path: /root/newgit
      state: directory
  - name: checkout git repo
    ansible.builtin.git:
      repo: https://github.com/PRATYUSHNAIR1976/pechuwar.git
      dest: /root/newgit
  
  - name: installing tomcat CentOS
    package:
      name: tomcat
      state: present
    when:  ansible_facts['os_family'] == "RedHat"
  - name: installing tomcat Ubuntu
    package:
      name: tomcat9
      state: present
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting tomcat CentOS
    service:
      name: tomcat
      state: started
    when:  ansible_facts['os_family'] == "RedHat"
  - name: starting tomcat Ubuntu
    service:
      name: tomcat9
      state: started
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting up tomcat CentOS 
    service:
      name: tomcat
      state: restarted
    when:  ansible_facts['os_family'] == "RedHat"
  - name: starting tomcat Ubuntu
    service:
      name: tomcat9
      state: restarted
    when:  ansible_facts['os_family'] == "Debian"
  - name: copying addressbook file CentOS
    copy:
      src: /root/newgit/addressbook.war
      dest: /usr/share/tomcat/webapps
    when:  ansible_facts['os_family'] == "RedHat"
  - name: copying addressbook file Ubuntu
    copy:
      src: /root/newgit/addressbook.war
      dest: /var/lib/tomcat9/webapps
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting up tomcat CentOS 
    service:
      name: tomcat
      state: restarted
    when:  ansible_facts['os_family'] == "RedHat"
  - name: starting tomcat Ubuntu
    service:
      name: tomcat9
      state: restarted
    when:  ansible_facts['os_family'] == "Debian"
